"Resource/UI/disguisestatuspanel_anim.res"
{
	"D1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"D1"
		"xpos"			"5"
		"ypos"			"rs1"
        "zpos"          "0"
		"wide"			"190"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/disguise/dis1"
		"scaleImage"		"1"
		"alpha"				"0"
	}
	"D2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"D2"
		"xpos"			"5"
		"ypos"			"rs1"
        "zpos"          "0"
		"wide"			"190"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/disguise/dis2"
		"scaleImage"		"1"
		"alpha"				"0"
	}
	"D3"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"D3"
		"xpos"			"5"
		"ypos"			"rs1"
        "zpos"          "0"
		"wide"			"190"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/disguise/dis3"
		"scaleImage"		"1"
		"alpha"				"0"
	}
	"D4"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"D4"
		"xpos"			"5"
		"ypos"			"rs1"
        "zpos"          "0"
		"wide"			"190"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/disguise/dis4"
		"scaleImage"		"1"
		"alpha"				"0"
	}
	"D5"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"D5"
		"xpos"			"5"
		"ypos"			"rs1"
        "zpos"          "0"
		"wide"			"190"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/disguise/dis5"
		"scaleImage"		"1"
		"alpha"				"0"
	}
}
